// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace SGAS.IdSvr.Entidade
{
   
    public class Usuario : IdentityUser<int>
    {
        public override int Id { get; set; }
        public string Password { get; set; }
        public string Genero { get; set; }
        public DateTime DataNascimento { get; set; }
        public string Nome { get; set; }

        [NotMapped]
        public virtual ICollection<FuncaoUsuario> FuncoesUsuarios { get; set; }
        public DateTime DataCriacao { get; set; }
        public DateTime DataAlteracao { get; set; }

        


    }
}